# Generated by Django 4.0.5 on 2022-06-28 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0002_trans_text1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trans',
            name='text1',
        ),
    ]
